### ISSUE TITLE
Materialization to Firebolt

### ISSUE THREAD

**Issue by dyaffe** [estuary/connectors#112]
Firebolt is essentially a Snowflake competitor that's up and coming but with good traction.  Because they only accept delta updates, they haven't been able to create integrations with the standard ELT providers (like Fivetran) or with Kafka.  That makes them a big near-term opportunity due to the fact that their customers want to take data from their Kafka clusters and other endpoints. 

We should create a materialization connector for Firebolt that works with delta updates.  [Here](http://docs.firebolt.io/) are their docs.  I can also provide credentials to a test account which they've provisioned to us.

**Comment by mdibaiee** [comment]
Studied Firebolt and our protocol to some extent and had a chat with Johnny and Phil. Here is my current high-level plan, and some notes for tackling this:

1. To add data to Firebolt tables ([fact and dimension tables](https://docs.firebolt.io/working-with-tables.html)), you need to create an External Table that is connected to a S3 bucket. The External Table basically gives you a SQL table interface to the data on S3, which can be saved in various formats (JSON documents or Parquet or ...).
2. You can then execute a query that copies data from this External Table to an actual fact or dimension table. The external table gives you two additional columns to filter on: `source_file_name` and `source_file_timestamp`.
3. Given the recent updates to our protocol, a new pattern has become available: [Recovery Log with Idempotent Apply](https://github.com/estuary/flow/blob/master/go/protocols/materialize/materialize.proto#L170-L204). This pattern matches how Firebolt works: we can store JSON documents on S3, commit them, and on the acknowledgement step copy them from the External Table to the actual table.

We initially preferred to write this connector after having completed the Rust transactor, but that can take a long time to be fully ready, whereas the Go transactor is robust and ready. As such, the decision is to write this connector in Golang using the transactor, however for parts where we need to translate our JSON schema into Firebolt table schemas, we prefer to write Rust crates and call them as binaries from the Go driver. Rust is better suited for such purposes given its Algebraic Data Types, and this will allow us to re-use this code more easily as we transition to using Rust for our connectors.

---

Some known unknowns at the moment:

1. Can we create the External Table as part of the driver or do we need to ask the user to create that table and give us a reference to it?

**Comment by psFried** [comment]
> Can we create the External Table as part of the driver or do we need to ask the user to create that table and give us a reference to it? (Apparently we can)

The approach we took with the Rockset connector was to have the connector try to create the Rockset collection it if it doesn't already exist. This allows users to create it themselves if they want, or let the connector do it. It also fits well with the general constraint that all `Apply` operations must be idempotent. The user needs to supply the name of the Rockset collection as part of the resource config. Of course there may be differences between Rockset and Firebolt, or other reasons to do things differently, but it may also be a good pattern to re-use here.
