### ISSUE TITLE
Request a connector to [DynomaDB | Postgres] [MacOS]

### ISSUE THREAD

**Issue by melody413** [estuary/connectors#1159]
### System Name

MacOS

### Type

Capture

### Details

Hi I am now migrating the DynamoDB to Postgres by using estuary.
But Postgres connector is not well.
How to set the Postgres address(host and port)?
Postgres server is running on my local PC.

Please help me asap.
Thanks

**Comment by melody413** [comment]
error:
the materialization cannot run due to the following error(s):
 - failed to connect to `host=localhost user=postgres database=postgres`: dial error (dial tcp [::1]:5436: connect: cannot assign requested address)

**Comment by dyaffe** [comment]
Hi @melody413,

We're happy to help you here! We're a cloud service so we generally connect to endpoints that can be accessed via the internet. If you have a database that's on localhost, the best bet is to set up a SSH tunnel as defined [here](https://docs.estuary.dev/guides/connect-network/#setup-for-aws) in our docs.

Let me know if you have any questions!

-Dave

**Comment by williamhbaker** [comment]
Going to close this out since I believe the issue has been resolved, but let us know if you have any other questions.
