### ISSUE TITLE
Request a connector to capture from SFTP via ssh keys

### ISSUE THREAD

**Issue by zhumo** [estuary/connectors#1164]
### System Name

SFTP via ssh keys

### Type

Capture

### Details

I have an SFTP system that uses ssh key auth rather than password. Would love to have that on the SFTP connector.

**Comment by dyaffe** [comment]
@zhumo this request makes a ton of sense.  We'll try to get it in for you asap and I'll let you know when we do.

**Comment by williamhbaker** [comment]
This was completed in https://github.com/estuary/connectors/pull/1202
