### ISSUE TITLE
add user agent connection string for Motherduck

### ISSUE THREAD

**Issue by dyaffe** [estuary/connectors#1166]

**Comment by dyaffe** [comment]
A custom_user_agent, that enables better customer issue diagnosis, as well as the ability to analyze cross-tool usage patterns of the data ecosystem tools connecting to MotherDuck.To add this option in JDBC, pass the custom_user_agent option through the properties map:

Properties config = new Properties();
config.setProperty("motherduck_token", token);
config.setProperty("custom_user_agent", "INTEGRATION_NAME");
Connection mdConn = DriverManager.getConnection("jdbc:duckdb:md:my_database", config);

The full diagnostic string consisting of DuckDB API, version, platform and the custom user agent value can then be queried:
PRAGMA USER_AGENT;

**Comment by williamhbaker** [comment]
We don't use JDBC for the connector, but I believe adding `custom_user_agent` to the connection string should work, for example `sql.Open("duckdb", "md:<database>?motherduck_token=<token>&custom_user_agent=<INTEGRATION_NAME>"`. Integration name could probably be `Estuary` (?)
