### ISSUE TITLE
OAuth2 Token Rotation can fail

### ISSUE THREAD

**Issue by Luishfs** [estuary/connectors#1416]
# Problem Description
While working with `source-hubspot` connector, an error ocurred where a user was not able to run that specific connector for a long period of time ( 15+ hours )

# Cause
This error happened because `source-hubspot`  access tokens are short-lived ( about 30 minutes ), so the amount of token rotations are plentiful.

While rotating, the class responsible for handling Oauth ( OAuth2Authenticator ) **does not** handle a time buffer for the expiration time of the token. Instead, this class calculates the expiration date ( in datetime ) and if the current time (pendulum.now() ) is older than the expiration date. If it is, then a token is rotated.
This means that there is a seconds windown in which a token can be expire and still be sent, causing a authentication error.

# Proposed solution
To fix this, i propose writing a time buffer inside the given class, to handle exactly the time output given by the `expires_in` field, and using this time buffer to compare if the token is **close** to expire, if so, expire it and rotate the token.

**Comment by williamhbaker** [comment]
@Luishfs was this closed by https://github.com/estuary/connectors/pull/1352? Or is this issue referring to something else?

**Comment by Luishfs** [comment]
@williamhbaker This was closed by #1352 ! Thanks for spotting it!
