### ISSUE TITLE
Enable conversion from OPENSSH key to RSA key

### ISSUE THREAD

**Issue by ghost** [estuary/connectors#144]
`thrussh` does not take OPENSSH private key, which is a common format from `ssh-keygen`.

Although the OPENSSH key could be converted to RSA key via the command `ssh-keygen -p -N "" -m pem -f id_rsa` manually, it is better to integrate this step in the connector and make it transparent to the user.

**Comment by mdibaiee** [comment]
We no longer need this since we switched to OpenSSH in network tunnel.
