### ISSUE TITLE
Azure Postgres Connector Failing due to cron auth

### ISSUE THREAD

**Issue by dyaffe** [estuary/connectors#147]
Our standard steps for setting up a Postgres database don't exactly work.  The first issue happens when one attempts to run the following:

```
postgres=> GRANT SELECT ON ALL TABLES IN SCHEMA information_schema, pg_catalog TO flow_capture;
WARNING: no privileges were granted for "sql_implementation_info"
ERROR: permission denied for table sql_parts
```

It next appears when trying to run a catalog set up to use this same database:

```
flowctl discover --image [ghcr.io/estuary/source-postgres:dev](http://ghcr.io/estuary/source-postgres:dev)
ERRO[0001] running connector failed                      error="exit status 1" logSource="[ghcr.io/estuary/source-postgres:dev](http://ghcr.io/estuary/source-postgres:dev)" operation=discover
FATA[0001] fatal error                                   err="fetching connector bindings: exit status 1 with stderr:\n\n{\"timestamp\":\"2022-03-08T22:47:29.876372355Z\",\"level\":\"INFO\",\"message\":\"received server public key: Ed25519(PublicKey { key: [52, 32, 85, 188, 70, 183, 144, 148, 34, 136, 135, 150, 154, 183, 205, 138, 126, 217, 47, 174, 194, 98, 72, 101, 233, 59, 251, 190, 154, 23, 231, 69] })\"}\ntime=\"2022-03-08T22:47:29Z\" level=info msg=\"initializing connector\" database=postgres host=localhost port=6000 slot=flow_slot user=flow_capture\n{\"timestamp\":\"2022-03-08T22:47:30.40290684Z\",\"level\":\"INFO\",\"message\":\"Unhandled global request: Ok(\\\"[hostkeys-00@openssh.com](mailto:hostkeys-00@openssh.com)\\\")\",\"log.target\":\"thrussh::client::encrypted\",\"log.module_path\":\"thrussh::client::encrypted\",\"log.file\":\"/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/thrussh-0.33.5/src/client/encrypted.rs\",\"log.line\":481}\nunable to list database columns: ERROR: permission denied for schema cron (SQLSTATE 42501)\nError:  unable to list database columns: ERROR: permission denied for schema cron (SQLSTATE 42501)\n"
```

The unable to list all database columns error appears to happen due to our flow_capture user not being able to grant usage on schema cron to `flow_capture`:

```
postgres=> GRANT USAGE ON SCHEMA cron TO flow_capture;
WARNING: no privileges were granted for "cron"
GRANT
```

Weirdly, the user Azure creates for us doesn't have this issue and can be granted those rights.  To reproduce this, I'm using [this](https://portal.azure.com/#@daveestuary.onmicrosoft.com/resource/subscriptions/c698039f-8a17-409b-95ef-65c94c538025/resourcegroups/test-group/providers/Microsoft.Compute/virtualMachines/dave-test-2/overview) VPN server to ssh and [this](https://portal.azure.com/#@daveestuary.onmicrosoft.com/resource/subscriptions/c698039f-8a17-409b-95ef-65c94c538025/resourceGroups/dave-test-vm_group/providers/Microsoft.DBforPostgreSQL/flexibleServers/test-postgres-estuary-db/overview) postgres db.  Please message me for a Flow catalog which can be used for the repro.

**Comment by willdonnelly** [comment]
So as far as I was able to tell when digging into this earlier, the problem stems from our table/column-discovery query, specifically the bit where it attempts to get the column description, and even more specifically the bit where it takes a table name (like `'cron.job'` in this case) and tries to cast it to an OID via `format('%s.%s',c.table_schema,c.table_name)::regclass::oid`. If the capture user doesn't possess the `USAGE` permission on some schema, the `::regclass` cast fails with a permission error and breaks the entire discovery process.

To be clear, there's nothing particularly special about the `cron` schema except that it exists and `flow_capture` doesn't have `USAGE` permission there. Unfortunately, the obvious solution of `GRANT USAGE ON SCHEMA cron TO flow_capture` doesn't appear to work in this situation, and we're not entirely clear why. There's infuriatingly little documentation on the intricacies of PostgreSQL permission management, so the best I can do is handwave in the direction of "maybe the default user that Azure PostgreSQL gives us isn't able to grant permissions to `flow_capture` in turn?"

I can see a ton of potential solutions or workarounds to this problem, not sure which is best:

1. Figure out the permission management issue, and then document what steps users should take when they hit an error like this to get the `flow_capture` user appropriate permissions.
2. Remove the column description feature from discovery, at least for the moment.
3. Custom-build a modified version of the `source-postgres` connector which removes column descriptions, and recommend people use that if they hit this issue but then use the latest `:dev` tagged build for the actual capture.
4. Add some sort of configuration setting to skip getting column descriptions, and tell people to enable that if necessary.
5. Remove the column description bits from the main column-discovery query, then issue N tiny little queries to request the description for each column of each table in turn. If one of these smaller queries fails then we can just default the description to `""` and keep going.

**Comment by willdonnelly** [comment]
After a bit more thought I realized that since we perform discovery at the start of every connector run for sanity-checking purposes, having a non-essential step which could potentially fail the entire capture like this goes from mildly annoying to Very Bad.

Happily it turned out that option 5 described in my previous comment was very easy to implement, so I've got a PR out now which should hopefully fix the issue.

**Comment by dyaffe** [comment]
Confirmed that this is fixed.
