### ISSUE TITLE
materialize-rockset: fix required fields

### ISSUE THREAD

**Issue by oliviamiannone** [estuary/connectors#150]
`api-key` should be the only required field in the endpoint config, but the generated spec from `schemalate` indicates that `http_logging` and `max_concurrent_requests` are, as well. Unsure where the inconsistency originates, but it's a bit of a confusing UX.

**Comment by williamhbaker** [comment]
@oliviamiannone is this still a problem? I'm thinking probably not since the fields in the endpoint config seem to have changed since this issue was opened originally, but let me know if it still is.

**Comment by oliviamiannone** [comment]
@williamhbaker Nope! Thanks for pointing this out
