### ISSUE TITLE
Various materialize connectors missing config descriptions

### ISSUE THREAD

**Issue by oliviamiannone** [estuary/connectors#153]
A critical part of the [connector docs](https://docs.estuary.dev/reference/Connectors/) are the tables generated from the configs. They look like this, and exist for both the endpoint config and resource/bindings:

| Property | Title | Description | Type | Required/Default |
|---|---|---|---|---|
| `/database` | Database | Name of the logical database to materialize to. | string |  |
| **`/host`** | Host | Host name of the database to connect to. | string | Required |
| **`/password`** | Password | User password configured within the database. | string | Required |
| `/port` | Port | Port on which to connect to the database. | integer |  |
| **`/user`** | User | Database user to use. | string | Required |

Right now, this is done manually using `flowctl api spec` and `schemalate`, which gives me a chance to edit them, but in the future it will likely be automated. The Title and Description also have UI implications (I would imagine). 

**So, all fields for both the endpoint and resource should have a descriptive title and a description that will output automatically.** Currently, most of the materialization connectors are missing at least some components. 

Here's a list of what's missing for each. I've also included connectors that are missing READMEs, because that seems important too, though it doesn't have immediate doc/UI implications:

*materialize-bigquery*
- Missing Title and Description for resource config
- Unsure about endpoint config - md generation fails due to https://github.com/estuary/flow/issues/406
- Possibly remove `credentials-file`, per https://github.com/estuary/flow/pull/367#discussion_r806427688 - from both config and README.

*materialize-elasticsearch*
- Missing Title from resource config
- In resource config, in the description for the field /field_overrides/-/pointer`, "delimited" is spelled incorrectly
- Missing Title and Description from endpoint config
- Missing README

*materialize-postgres*
- Missing Title and Description from resource and endpoint configs
	- As of this ticket creation, [I wrote my own.](https://github.com/estuary/flow/blob/785b0d5388d97af284b7523484289eafedf2d727/site/docs/reference/Connectors/materialization-connectors/PostgreSQL.md)
- Missing README

*materialize-rockset*
- Missing Title and Description from resource and endpoint configs
	- As of this ticket creation, I [wrote my own.](https://github.com/estuary/flow/blob/4f2ca48fda98b608dd2dc2d920dc40ecc60150f5/site/docs/reference/Connectors/materialization-connectors/Rockset.md)

*materialize-s3-parquet*
- Missing Title and Description from resource and endpoint configs
- Missing README

*materialize-snowflake*
- Missing Title and Description from resource and endpoint configs
- Missing README

**Comment by mdibaiee** [comment]
Noted for Firebolt connector, will make sure we have these for that one 👍🏽

**Comment by mdibaiee** [comment]
For reference, this is how I added title and description to the configurations of Firebolt connector: https://github.com/estuary/connectors/pull/146/commits/a28f9385e6417afe17ee50baada4e2d5222546d8

**Comment by williamhbaker** [comment]
I'm not aware of any additional issues for the noted connectors. They've all undergone signifiant revisions since this issue was originally opened.
