### ISSUE TITLE
Consider using schemalate to generate Rockset ingest SQL transformations

### ISSUE THREAD

**Issue by psFried** [estuary/connectors#162]
I recently learned about the [ingest SQL transformation](https://rockset.com/docs/rollups/) feature, and it got me thinking.
We could potentially use `schemalate` to generate an ingest SQL transformation that matches the behavior of the `reduce` annotations of the Flow collection. If we did, then it would, at least theoretically, allow the (delta_updates) materialization to produce results that look more or less identical to what you'd get with delta_updates disabled. For example, given a Flow collection JSON schema like:

```yaml
type: object
properties:
  id: {type: integer}
  total:
    type: integer
    reduce: {strategy: sum}
required: [id, total]
```

We could generate an ingest SQL transformation like:

```sql
select
  id,
  SUM(total) as total
FROM
  _input
GROUP BY
  _id;
```

Then the materialization of multiple Flow documents (`{id: 1, total: 3}, {id: 1, total: 4}`) would result in a single document in Rockset with the reductions applied (`{id: 1, total: 7}`).

Of course it's possible that not all Flow reduction annotations will have corresponding sql aggregation functions in Rockset with identical behavior, and we'll need to investigate that before going too far on any implementation.

**Comment by williamhbaker** [comment]
Closing this since I don't think we'll need it with the recent Rockset aquisition
