### ISSUE TITLE
Request a connector to materialize to Tinyibrd

### ISSUE THREAD

**Issue by danthelion** [estuary/connectors#1635]
### System Name

Tinybird

### Type

Materialize

### Details

It would be great if we could materialize data into Tinybird. They offer an [Events API](https://www.tinybird.co/docs/ingest/events-api#send-batches-of-json-events), which accepts singular or batched events via an HTTP endpoint.

**Comment by williamhbaker** [comment]
I'm gonna call this one done via dekaf.
