### ISSUE TITLE
Request a connector to [capture from | materialize to] [your favorite system]

### ISSUE THREAD

**Issue by tebrown** [estuary/connectors#1715]
### System Name

SFTP (realtime)

### Type

Capture

### Details

Ideally, when a file is written, it would be immediately processed through the pipeline.

**Comment by dyaffe** [comment]
Hey @tebrown -- thanks for reaching out.  We can actually do that with the current connector.  It's possible to set an interval at which our connector would look for new files.

`interval` is a top-level field once you've set up the connector which can be configured as low or high as you want.  If you want it to run every second, that would be possible.  You can configure it like `interval: 5s`

**Comment by tebrown** [comment]
Oh, neat!  I somehow missed that.
