### ISSUE TITLE
materializations: expand custom DDL config to better handle very large integers and numbers

### ISSUE THREAD

**Issue by williamhbaker** [estuary/connectors#1721]
Numeric fields can be represented in 4 general ways in JSON schema, and their materialized columns are created differently in each case:

- `type: integer`
  - Usually materialized as a `BIGINT` or similar column, which have the range of a 64 bit signed integer
- `type: number`
  - Usually materialized as a double precision column, with a possibility of values being approximate
- `type: string, format: integer`
  - Often materialized as an arbitrary precision numeric column, with a scale of `0` and precision as the maximum allowed. This allows for storing exact values of large integers, for example a `NUMERIC(38,0)` column can hold an integer that is 38 digits long
  - Also applies to `type: [string, integer], format: integer` etc.
- `type: string, format: number`
  - Ideally this would be materialized as as an arbitrary precision numeric column to preserve the value exactly. In practice only `materialize-postgres` supports a “unconstrained numeric” column like `NUMERIC`/`DECIMAL` and so it is the only materialization that uses this. All others use the same double precision column types as they would for a `type: number`.
  - Also applies `type: [string, number], format: number` etc.

These columns work well in the vast majority of cases, but there can be issues if the values are uncommonly large.

For `type: integer` fields, a possible scenario is for the values to exceed the limits of a 64 bit signed integer column. These values are still valid `type: integer` per JSON schema. Attempting to load these values into such columns will cause the materialization to fail. `type: string, format: integer` fields similarly have the potential to exceed 38 digits (for example, or whatever the limit of the system is) in length and will cause the materialization to fail. `type: string, format: number` fields could also exceed the maximum possible length limit if a materialization creates a column with a limited precision for them. Fields that are materialized into double precision columns like `number` and often `type: string, format: number` are pretty unlikely to contain values that are larger than can be stored, although their values may be approximate.

The proposed improvement is to allow users to provide configuration via field selection that can override the default column DDL. We have already done [a limited implementation](https://github.com/estuary/connectors/pull/1562) for defining custom DDL on a per-field basis, and this will be broadened to work for all columns, with the caveat that the standard value serialization is compatible with the alternate DDL. For example: Typically a `type: string, format: integer` column is serialized as a JSON integer. It would work to set custom DDL for this field as `DECIMAL(20)`, but not with custom DDL of `TEXT`. 

In this way `type: integer` and `type: string, format: integer` fields could have custom DDL set to things like `DECIMAL(38)` or `DOUBLE PRECISION` to allow for materializing very large values with or without the potential for approximation, depending on just how large the values are. `type: number` and `type: string, format: number` could also have custom DDL like `DOUBLE PRECISION` set for them

For this manual intervention to work at all, we need to have good error messages from the connector that describe which collection and fields are out of range so that the user can know which ones need custom DDL set.

One possible future addition could be the ability to materialize any type of field as a stringified value, so that any possible numeric value could be materialized in a `TEXT` type of column without a loss of accuracy.

**Comment by jgraettinger** [comment]
A related case that's come up recently is the newly-added `JSON` type in BigQuery. We continue to use `TEXT` for JSON objects and arrays only due to the migration burden for existing materializations, which this could help alleviate.

**Comment by williamhbaker** [comment]
Completed in https://github.com/estuary/connectors/pull/1801
