### ISSUE TITLE
Fix flow_watermarks in CDC Captures 

### ISSUE THREAD

**Issue by dyaffe** [estuary/connectors#190]
Problem:

Currently when a user captures data from a database such as Postgres or MySQL, we automatically discover and capture from the flow_watermarks table.  This obviously isn't something that would be useful for the user so it would be ideal to stop that behavior.

Potential solution:

It would be ideal for us to create flow_watermarks under a different non-public schema for the user.  This would ensure that we wouldn't find it when capturing from the database while also not polluting the database's schemas.

We automatically try to create flow_watermarks, so a solution here would involve updating that creation process as well as our docs which contain SQL queries to create flow_watermarks.

**Comment by willdonnelly** [comment]
Requiring that the watermarks table be in a separate schema seems like it would cause more problems than it solves.

What if we just did the dumbest thing that could work, and modified the `discover` subcommand's implementation to remove the specific stream whose name+namespace matches the watermark table before outputting the discovered catalog?

**Comment by dyaffe** [comment]
That seems like a plan to me
