### ISSUE TITLE
new connector: source-brevo

### ISSUE THREAD

**Issue by jonwihl** [estuary/connectors#1915]
Native connector for [Brevo](https://developers.brevo.com/reference/getting-started-1)

Streams

- [ ] Transactional Emails
- [ ] Transactional SMS
- [ ] Inbound Parsing
- [ ] Transactional WhatsApp
- [ ] Email Campaigns
- [ ] SMS Campaigns
- [ ] WhatsApp Campaigns
- [ ] Contacts
- [ ] Events
- [ ] Accounts
- [ ] Senders
- [ ] Domains
- [ ] Webhooks
- [ ] Users
- [ ] Processes
- [ ] External Feeds
- [ ] Companies
- [ ] Deals
- [ ] Tasks
- [ ] Notes
- [ ] Files
- [ ] Conversations
- [ ] Ecommerce
- [ ] Coupons
- [ ] Payments

**Comment by jameswinegar** [comment]
[Contacts](https://api.brevo.com/v3/contacts)
[Contacts Attributes](https://api.brevo.com/v3/contacts/attributes)
[Contacts Lists](https://api.brevo.com/v3/contacts/lists)

The use case is bi-directional syncing with HubSpot lists

**Comment by jameswinegar** [comment]
Could we add https://developers.brevo.com/reference/getcontactsfromlist ?

**Comment by thisadam** [comment]
I'm keen on this as well
