### ISSUE TITLE
source-mysql error inserting to watermarks table

### ISSUE THREAD

**Issue by psFried** [estuary/connectors#197]
We observed a failing shard for a source-mysql capture, which looks like it was never able to get started due to an error inserting into the watermarks table. This seems like it's potentially just a misconfiguration (an assumption we should validate). If so, then the real issue here is just that we should ideally surface that error during Validate so that we can give more immediate feedback to the user. I've attached the task logs here.

[mysql-logs.zip](https://github.com/estuary/connectors/files/8689999/mysql-logs.zip)

**Comment by willdonnelly** [comment]
It should ~always be safe to go do a watermark write at any time, so adding this to Validate should be almost trivial.

**Comment by williamhbaker** [comment]
Closing this out since we now do these kinds of checks in Validate
