### ISSUE TITLE
source-postgres error starting replication

### ISSUE THREAD

**Issue by psFried** [estuary/connectors#198]
We observed a failing shard for a source-postgres capture, which looks like it was never able to get started due to an error connecting to the database. This seems like it's potentially just a misconfiguration (an assumption we should validate). If so, then the real issue here is just that we should ideally surface that error during Validate so that we can give more immediate feedback to the user. I've attached full the task logs here, but the most relevant bit is probably:

```
{
  "_meta": {
    "uuid": "0204b87e-d242-11ec-8400-7de26a7ce094"
  },
  "shard": {
    "name": "estuary/dave-tw/postgres-rds/source-postgres",
    "kind": "capture",
    "keyBegin": "00000000",
    "rClockBegin": "00000000"
  },
  "ts": "2022-05-12T22:22:28.518064913Z",
  "level": "info",
  "message": "error starting replication: unable to connect to database for replication: failed to connect to `host=database-2.ccpi9kwz3vei.us-east-1.rds.amazonaws.com user=postgres database=fruit`: server error (FATAL: no pg_hba.conf entry for replication connection from host \"34.132.76.64\", user \"postgres\", SSL on (SQLSTATE 28000))",
  "fields": {
    "logSource": "connector stderr",
    "operation": "read"
  }
}
```

[pg-logs.zip](https://github.com/estuary/connectors/files/8690054/pg-logs.zip)

**Comment by willdonnelly** [comment]
It looks like I was right to be worried. The current way that the `source-postgres` replication streaming logic handles WAL cursors and acknowledgement means that it will potentially advance the slot LSN if it's invoked with an empty restart cursor value. So there's a danger here if Validate is done after a working capture already exists using a particular slot. Is that a thing which can happen? It feels like it's probably something that needs to be accounted for.

**Comment by psFried** [comment]
Yeah, Validate can be called at any time. Would it be possible to address this by logging a more specific error message about the authorization? That's the only other option that really comes to mind for me.

**Comment by williamhbaker** [comment]
@willdonnelly I _think_ we can close this now, since we have added a lot of checks for these kinds of things to Validate. I'm not actually 100% sure though. Is there anything more to be done here?

**Comment by willdonnelly** [comment]
I think this can be closed, the core issue in this particular case was that the user wasn't actually authorized for replication, and we now check for that permission during validation.
