### ISSUE TITLE
Request a connector from Supabase to Hubspot

### ISSUE THREAD

**Issue by moorekevin** [estuary/connectors#2017]
### System Name

Supabase

### Type

Both

### Details

Hi I saw that you posted that you are testing a connector between Supabase and Hubspot on this thread, https://community.hubspot.com/t5/HubSpot-Ideas/Supabase-integration/idi-p/865110

Is this something I can get access to?

**Comment by dyaffe** [comment]
Hey @moorekevin  -- that article refers to our capability to create a [capture from Supabase](https://docs.estuary.dev/reference/Connectors/capture-connectors/PostgreSQL/Supabase/) and then sync using a [webhook sync to Hubspot](https://docs.estuary.dev/reference/Connectors/materialization-connectors/http-webhook/).

Let us know if you need any extra info.
