### ISSUE TITLE
source-impact-native: Refactor stop date

### ISSUE THREAD

**Issue by jonwihl** [estuary/connectors#2206]
![Image](https://github.com/user-attachments/assets/f72b3ba5-8ebb-4740-9208-bc74851af641)

The stop_date language is confusing and counter-intuitive for the usual start_date config. Please verify if this feature is necessary and replace it with a start_date if possible

[PR #2186](https://github.com/estuary/connectors/pull/2186) fixes this.

**Comment by Alex-Bair** [comment]
Addressed in https://github.com/estuary/connectors/pull/2186.
