### ISSUE TITLE
GCS Strangeness with Nested Buckets

### ISSUE THREAD

**Issue by dyaffe** [estuary/connectors#225]
**Problem**
I'm attempting to save and publish a capture from Google Cloud storage and finding some weird behavior with nested buckets.  The bucket I'm using is called "estuaryflowexamples" in our GCS account.  All files under that bucket are public.  There is a non-public folder below it which also has public files.  I'm connecting to it using an IAM user with Storage Object Admin permissions, so none of that should really matter.

The discover works fine but when I go to save and publish, I get the following error which I'm not sure how to fix:

```
Waiting for logs...
file:///flow.json error at /collections/estuary~1dave~1test-gcs-csv~1estuaryflowexamples :
collection estuary/dave/test-gcs-csv/estuaryflowexamples is a prohibited prefix of collection estuary/dave/test-gcs-csv/estuaryflowexamples/Foursquare, defined at file:///flow.json#/collections/estuary~1dave~1test-gcs-csv~1estuaryflowexamples~1Foursquare
FATA[0000] fatal error                                   err="1 build errors"
Copying file:///tmp/.tmp6lGO08/builds/064a103be27b8c00 [Content-Type=application/octet-stream]...
/ [0 files][    0.0 B/168.0 KiB]                                                
/ [1 files][168.0 KiB/168.0 KiB]                                                

Operation completed over 1 objects/168.0 KiB.                                
```

**Comment by williamhbaker** [comment]
@dyaffe I was able to discover, save & publish from this collection today. It's possible that something changed between this issue originally being opened & now that resolved this problem. Do you know if this is still an issue, or can we mark this done?

**Comment by jgraettinger** [comment]
A change we made between this issue being filed and now is that the discover RPC no longer attempts to map directory-like prefixes into distinct file streams and we instead just emit a single stream, so I believe this is no longer applicable.

**Comment by williamhbaker** [comment]
Going to mark this as done since it seems like it is.
