### ISSUE TITLE
Specific Amazon S3 Discover Runs Forever

### ISSUE THREAD

**Issue by dyaffe** [estuary/connectors#227]
**Problem**
If I run discover via our UI on the bucket `daves-test-bucket-1234562`, it runs forever without exiting.

It will work if I add a match key, however.
 
cc'ing @jgraettinger since he was working on this connector.

**Comment by williamhbaker** [comment]
Tested this out today and it doesn't run forever anymore. It finishes fairly quickly now, prior to even the timeouts that we have added for discovery. Going to close this issue out, but feel free to re-open if there are still problems.
