### ISSUE TITLE
Switch from :dev to :v1 tags for connectors

### ISSUE THREAD

**Issue by psFried** [estuary/connectors#242]
- Connectors main build should push both `:dev` and `:v1` tags
- Switch existing production tasks to `:v1` tag
- Switch the UI to default to using the `:v1` tag

**Comment by mdibaiee** [comment]
For our connectors:
- https://github.com/estuary/connectors/pull/243

For airbyte connectors:
- https://github.com/estuary/airbyte/commit/e5b4dc9a0574c9a3b55e254df35510fc3bb2d4d2
