### ISSUE TITLE
Can't Delete Firebolt Materializations with Missing Tables

### ISSUE THREAD

**Issue by dyaffe** [estuary/connectors#245]
**Problem**
I just tried to delete a Firebolt materialization in which the table corresponding to it was previously removed (or never existed).  You can reproduce it by deleting: estuary/dave-test/ga-locations-demo

**Here's some logs around the issue**

`select ll.log_line from public.draft_specs as ds join public.publications as p ON p.draft_id = ds.draft_id join internal.log_lines as ll on ll."token" = p.logs_token where ds.catalog_name = 'estuary/dave-test/ga-locations-demo';`

`[31mFATA[0m[0002] fatal error                                   [31merr[0m="deleting materialization \"estuary/dave-test/ga-locations-demo\": exit status 1 with stderr:\n\nrunning table drop query: response error code 500, Code: 10001, e.displayText() = DB::Exception: Invalid operation error: Did not find a table or view with name ga_locations_demo (version 21.6.5.1)\n\n"`

CCing @mdibaiee in case he has thoughts

**Comment by mdibaiee** [comment]
@dyaffe I think we do the same thing in all other materializations that we have (I just checked our SQL materializations, they also return an error if the database doesn't exist).

Should we change this across the board? It seems reasonable that a user might have deleted a materialized table for any reason, and now they want to delete the materialization in Flow. Although I think it is preferrable to let them know about this. I'm wondering if this can be a feature on Flow Control Plane where you can "force-delete" a materialization even if ApplyDelete RPC fails. cc @jgraettinger @psFried

**Comment by psFried** [comment]
It's intended for `ApplyDelete` to be idempotent, just like `ApplyUpsert`, so I think it makes sense to have connectors handle a missing resource by just returning successfully. My 2 cents is that it's fine to just log that the database is missing and move on, and that we should do that across the board in all of our materialization connectors.

**Comment by mdibaiee** [comment]
Fixed in https://github.com/estuary/connectors/pull/250
