### ISSUE TITLE
Can't delete Materializations to Rockset

### ISSUE THREAD

**Issue by dyaffe** [estuary/connectors#254]
**Problem**
Attempting to delete materializations to Rockset results in this error:

`[31mFATA[0m[0002] fatal error                                   [31merr[0m="deleting materialization \"estuary/phil/test-mat-rockset\": exit status 1 with stderr:\n\npanic: runtime error: invalid memory address or nil pointer dereference\n[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x9c19e7]\n\ngoroutine 1 [running]:\ngithub.com/estuary/flow/go/protocols/materialize.(*ApplyResponse).MarshalToSizedBuffer(0x0, {0xc000130204, 0x0, 0x1})\n\t/go/pkg/mod/github.com/estuary/flow@v0.1.1-0.20220412155258-453bb0e503ea/go/protocols/materialize/materialize.pb.go:2581 +0x27\ngithub.com/estuary/flow/go/protocols/materialize.(*ApplyResponse).MarshalTo(0x1324178, {0xc000130204, 0x0, 0xc000300004})\n\t/go/pkg/mod/github.com/estuary/flow@v0.1.1-0.20220412155258-453bb0e503ea/go/protocols/materialize/materialize.pb.go:2577 +0x98\ngithub.com/gogo/protobuf/io.(*uint32Writer).WriteMsg(0xc000516000, {0xd7e5d8, 0x0})\n\t/go/pkg/mod/github.com/gogo/protobuf@v1.3.2/io/uint32.go:87 +0x12b\ngithub.com/estuary/connectors/materialize-boilerplate.applyDeleteCmd.Execute({{{0xd874a8, 0xc0002d0100}, {0xd8b8d8, 0x1324178}, 0xc00012c180, {0x7fbf2000b008, 0xc000516000}}}, {0xc000282560, 0x0, 0x1})\n\t/builder/materialize-boilerplate/boilerplate.go:161 +0xf9\ngithub.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc000284d90, {0xc000032050, 0x1, 0x1})\n\t/go/pkg/mod/github.com/jessevdk/go-flags@v1.5.0/parser.go:335 +0x94e\ngithub.com/jessevdk/go-flags.(*Parser).Parse(...)\n\t/go/pkg/mod/github.com/jessevdk/go-flags@v1.5.0/parser.go:191\ngithub.com/estuary/connectors/materialize-boilerplate.RunMain({0xd8b8d8, 0x1324178})\n\t/builder/materialize-boilerplate/boilerplate.go:43 +0x6c5\nmain.main()\n\t/builder/materialize-rockset/cmd/connector/connector.go:18 +0xda\n"`

cc @psFried

**Comment by williamhbaker** [comment]
I've been able to delete rockset materializations recently without issue, so I'm going to close this out.
