### ISSUE TITLE
Bigquery `ApplyDelete` always fails to drop tables

### ISSUE THREAD

**Issue by psFried** [estuary/connectors#283]
Bigquery doesn't support DDL statements inside of transactions, but the [`sql.Driver` implementation](https://github.com/estuary/flow/blob/6e8e83ebd8ff73f4817223cb476e16ed03f8091e/go/protocols/materialize/sql/driver.go#L262) of `ApplyDelete` always creates statements that run inside of a transaction. So whenever you delete a Bigquery materialization in Flow, you get this error in the logs:

```
applying schema updates: query: wait: googleapi: Error 400: Query error: DDL statements are not supported in a transaction, except for those creating or droping temporary tables or temporary functions. at [1:279], invalidQuery
```

One possible approach would be to move the transaction handling (`BEGIN` and `COMMIT`) into `Endpoint.ExecuteStatements`, and just have Bigquery not use a transaction at all. Another approach might be to find a way for the Bigquery connector to add the magic comment `--**bigQueryOmitFromTransaction**` just before each DDL statement.

**Comment by williamhbaker** [comment]
Closing this since it has been fixed
