### ISSUE TITLE
Google Cloud Storage Renderer Issue

### ISSUE THREAD

**Issue by dyaffe** [estuary/connectors#286]
**Problem**
The UI currently shows an error message saying "No applicable renderer found" when attempting to discover from our Google Cloud Storage connector.

It sounds like this is a schema mismatch issue between the front and backend:

<img width="1393" alt="Screen Shot 2022-07-11 at 11 39 38 AM" src="https://user-images.githubusercontent.com/8095717/178325633-a51b0663-4b7d-4b16-9a97-024639b29d63.png">

@mdibaiee since he mentioned he could help

**Comment by mdibaiee** [comment]
@dyaffe I actually can't reproduce this on dashboard.estuary.dev:

<img width="1232" alt="image" src="https://user-images.githubusercontent.com/2807772/178337793-b7693bf6-a2b5-4a1e-abb9-662032bc7b74.png">


Can you try again?

**Comment by dyaffe** [comment]
Just did and I'm still seeing it -- it happens after you hit discover which it doesn't appear that you did in the screenshot since not everything is filled out

**Comment by mdibaiee** [comment]
@travjenkins I have a feeling that this is a frontend bug. The form renders correctly to begin with, but once the discover button is pressed it breaks. From network I can't see any request that would lead to a different schema. This seems to happen specifically for multi-line secret fields

**Comment by mdibaiee** [comment]
This seems to have been fixed. @dyaffe can you confirm if you can still reproduce this bug? Travis fixed this here I think: https://github.com/estuary/ui/pull/266

**Comment by dyaffe** [comment]
Confirmed, this is working now.
