### ISSUE TITLE
Support server-side-events (SSE) protocol in source-http-file

### ISSUE THREAD

**Issue by mdibaiee** [estuary/connectors#298]
For example:

```
curl -v -H 'Accept: application/json' https://stream.wikimedia.org/v2/stream/recentchange
```

These endpoints do not support `HEAD` requests usually.

**Comment by jgraettinger** [comment]
Changing scope a bit: if we sent `Accept: application/json` than we get the desired stream of JSON documents, so as an alternative we can do this. We also need to not send a HEAD request (as we currently do) since the server may not support it.

**Comment by williamhbaker** [comment]
Closing this per the referencing commits
