### ISSUE TITLE
Update our Snowflake Connector Config

### ISSUE THREAD

**Issue by dyaffe** [estuary/connectors#334]
**Problem**
With AWS Snowflake, at least in `US-WEST-2`, we are currently seeing an issue where we are unable to connect to snowflake with a URL in the format we try with which is:

https://CLIENTID.REGIONID.CLOUDPROVIDER.snowflakecloudcomputing.com

Their connection URL that works is:

https://CLIENTID.snowflake.computing.com

**Proposal**
It occurs to me that the best thing we could do from a users perspective might be to ask for it in the UI in the following format:

https://   USER INPUT HERE  .snowflakecomputing.com 

Then users could update whatever they see in their actual snowflake instance and we could possibly parse it (if required from there).

I could be totally wrong about the plan but this seems reasonable.

**Comment by willdonnelly** [comment]
Purely on aesthetic grounds I would recommend going a step further and just asking for the full domain.

Conveniently the Snowflake client library we use accepts an optional `Host` config property which supersedes their "assemble a domain name from Region and Account and stuff" logic, so I believe that the whole mess of options could be ripped out entirely and replaced with just `Host`.

**Comment by psFried** [comment]
The snowflake client also seems to have special handling for the `us-west-2` region, which makes me wonder whether the configuration specified `US-WEST-2` or `us-west-2`. @dyaffe are you able to confirm which one was in there?

**Comment by dyaffe** [comment]
It looks like we tried it with capitals.  The draft ID was `07:37:2a:db:80:fb:a8:00`

**Comment by williamhbaker** [comment]
I think it will probably work if it is tried with lower-case letters: `us-west-2`. That will cause the DNS logic in the snowflake client [here](https://github.com/snowflakedb/gosnowflake/blob/5da2ab2463b2c7e544722bc58defdb23397287d6/dsn.go#L99-L111) to make the "host" be `account` + `.snowflakecomputing.com`, which I think lines up with what you said works in the original issue (`https://clientid.snowflake.computing.com/` - assuming there's an extra `.` in there and it should actually be `https://clientid.snowflakecomputing.com/`)

Seems like `us-west-2` is special somehow in snowflake's system and the URL for us-west-2 shouldn't contain the region. I can only speculate as to why that would be.

I'll try this out myself and see if I can repro the issue.

**Comment by williamhbaker** [comment]
Looks like it will take more than just lower-casing the region, since our connector is appending the region with the cloud provider: https://github.com/estuary/connectors/blob/17e0b95592ff8abfd927742fcdc3044f60d5ca46/materialize-snowflake/snowflake.go#L45

So using `us-west-2` on `aws`, you end up with a region of `us-west-2.aws`, which obviously doesn't work.

**Comment by williamhbaker** [comment]
Looks like when using the identification method of [account locating in a region](https://docs.snowflake.com/en/user-guide/admin-account-identifier.html#format-2-legacy-account-locator-in-a-region), the actual format for the "region" part can [vary quite a bit](https://docs.snowflake.com/en/user-guide/admin-account-identifier.html#non-vps-account-locator-formats-by-cloud-platform-and-region) for AWS. It can be anything from just the account ID (like for `us-west-2`), to `<account id>.<region>` (ex: `xy12345.us-east-1`), to `<account id>.<region>.<provider>` (ex: `xy12345.us-east-2.aws`).

The current connector logic is generalizing it into the common non-AWS form, but for AWS providers this isn't always the case. Seems like @willdonnelly's suggestion for asking for the full domain is the only way to handle this. I'll start working on that now. We'll probably also need to support [orgname-accountname](https://docs.snowflake.com/en/user-guide/admin-account-identifier.html#format-1-preferred-account-name-in-your-organization) format in the near-future.

**Comment by williamhbaker** [comment]
Closed by https://github.com/estuary/connectors/pull/335
