### ISSUE TITLE
source-postgres: validation doesn't verify that source table exists

### ISSUE THREAD

**Issue by williamhbaker** [estuary/connectors#338]
When creating a capture with source-postgres, validation does not seem to verify that the source table exists. It is possible to create a capture where the source table does not exist and publish it, which immediately fails at run time with an error: `primary key in catalog differs from database table`. 

I was surprised that that validation did not check to make sure that the source table exists. Unless it was some error on my part, it seems like it pretty easily could check for this on validation.

**Comment by willdonnelly** [comment]
If I recall correctly (and this is off the top of my head so I could be mistaken) captures using the Airbyte protocol don't have access to any catalog information during validation -- they're solely checking that the provided config appears correct as far as connecting to the database and whatnot.

Once I finish migrating SQL captures to the Flow gRPC protocol I believe it would be possible to improve this.

**Comment by williamhbaker** [comment]
Duplicate issue was created in https://github.com/estuary/connectors/issues/461 - going to close this one since that one has a concrete example, although they are fundamnetally the same.
