### ISSUE TITLE
Pre-fill Connector Materialization Binding Names 

### ISSUE THREAD

**Issue by dyaffe** [estuary/connectors#380]
**Problem**
I wrote this up as a [UI ticket](https://github.com/estuary/ui/issues/311) originally, but it also needs a connectors equivalent.

At a high level, we currently require that users enter the name of every binding that they want to push data to manually in the UI.  This is problematic because there can be 50+ of them and it takes a long time.  What users generally do is fill the name out in the form of:  source_connector_name._.collection_name(after last `/`).  Ex. if the source you're connecting from is postgres and your collection name is estuary/test/2345/table234, we'd push `postgres_table234` as the materialization name.

The UI can not do this on its own because it doesn't know what the name field a connector uses is.  

**Proposal**
Phil said a good solution to this would be to pass an annotation from the connector which describes which field is its name.

**Comment by mdibaiee** [comment]
@dyaffe this is more tricky than just a name. Most of our connectors might only have some sort of a "name" field that they need, but we allow arbitrary configuration to be specified to each binding, so it's not easy to auto-fill these values from a single value.

What I can see as possible is allowing connector developers to define *default templates* that would allow us to fill values for each field according to a template.

As an example, for materialize-google-sheets we could have:

```
sheet:
  defaultTemplate: "{{ collection.name | slash_to_underscore }}"
```

where `slash_to_underscore` turns the slashes in a collection name to underscores, this would allow us to auto-fill binding names in materialize-google-sheets bindings to something like: `estuary_test_intercom_teams` for collection `estuary/test/intercom/teams`. A different example:

```
sheet:
  defaultTemplate: "{{ collection.name | omit_tenant | slash_to_underscore }}"
```

This would omit the tenant piece, evaluating to `test_intercom_teams`.

**Comment by dyaffe** [comment]
Thanks @mdibaiee this makes sense to me.  I'd be happy to have this as config in supabase too if it makes it easier to implement or so that devs don't have to stay on top of things.

**Comment by mdibaiee** [comment]
Johnny's suggestion: instead of the connector changing the value, use the value as-is and allow a validation to be done on the value so if the identifier is not valid by the connector's requirements, we can ask the user to fix it

**Comment by mdibaiee** [comment]
@jgraettinger I'm imagining the case where the collections have slashes in most of them, and if the user has to go through all of them manually to fix them, we are back to square one. This can happen with captures such as FIrestore which use slashes for sub-collections, etc.
