### ISSUE TITLE
Connectors should allow the runtime to choose the port that they listen on

### ISSUE THREAD

**Issue by psFried** [estuary/connectors#392]
Now that connectors listen on a TCP socket, it prevents using them with `--network=host`. The simple fix suggested by @willdonnelly was to update connectors allow configuring the port they listen on using an environment variable. Then the runtime can assign a unique port to each one.

**Comment by willdonnelly** [comment]
On further consideration I think a flag would probably be better, since we'd need to make sure that all connectors support the flag before changing the runtime to handle the assignment anyway, and at that point we'd want things to break cleanly if some connector hasn't been updated properly.

**Comment by mdibaiee** [comment]
Closing this as we have changed our approach towards TCP sockets
