### ISSUE TITLE
Request a connector to capture from Mongo

### ISSUE THREAD

**Issue by loremaps** [estuary/connectors#508]
### System Name

Mongo

### Type

Both

### Details

It would be great if we can capture from/materialize to MongoDB (and Mongo Atlas)

**Comment by dyaffe** [comment]
Thanks @loremaps, we are planning on adding that connector soon and will keep you updated via this ticket.  If you could elaborate on your use case, we can potentially accelerate building it.

**Comment by loremaps** [comment]
Hi @dyaffe! Our main goal is to replicate data from an application that uses mongoDB to a postgres database for running "analytics". This is quite similar to what airbyte offers as "full refresh | overwrite".

I am not sure if I answered your question, please let me know if you have need more info.

**Comment by dyaffe** [comment]
That's helpful.  We have a Firestore connector now which operates similarly @loremaps.  It does offer the ability to do schema inference on data before pushing it to a DB or warehouse for easier analytics and our MongoDB connector will do the same when available.

We will keep you updated.

**Comment by dyaffe** [comment]
Hey @loremaps, we are planning on picking up work on the MongoDB capture connector now.  Let me know if you'd still be interested in being a design partner for it -- if so, we will probably have this ready to try in a couple of weeks.

**Comment by dyaffe** [comment]
Hey @loremaps, the MongoDB is now ready for generalized usage.  It won't work for Mongo Atlas or other providers that use `mongodb+srv://` schema.  We'll be adding that but currently support and default to `mongodb://`.  

Let us know if you need that but otherwise this is ready.  Feel free to add any questions you may have here.

**Comment by dyaffe** [comment]
Hey @loremaps this is now live and available.  Please feel free to give it a go and let us know if you have any questions.  

One quick thing -- Estuary has the ability to do schema inference on your data for you if you'd like.  Generally speaking it's good to wait until a decent amount of data has been captured before doing it.  That can be done by navigating to your capture, selecting the three dots next to it then "edit specification".  Click the "specification" subtab and then "schema inference".  If you don't do this, we'll push JSON documents to your destination system which may or may not be desirable.

Please feel free to reach out here or on our Slack if you have questions.

**Comment by loremaps** [comment]
Hey @dyaffe thank you! I already created a source 👍 I will have a closer look this week and let you know on Slack. Thanks!

**Comment by dyaffe** [comment]
Sounds good, thanks @loremaps
