### ISSUE TITLE
Materialization Testing Framework

### ISSUE THREAD

**Issue by snowzach** [estuary/connectors#51]
We would like to build a materialization connector testing framework that can drive connectors directly without the Flow Runtime. It should be able to provide details/reporting around:

Correctness
* Storing correct values
* Subsequent upserts ending with the correct values (transactions in correct order etc)

Performance
* Records per second
* Bytes/Second
* Transactions per time frame
* Optimal transaction size determination

**Comment by williamhbaker** [comment]
Closing this since it is done!
