### ISSUE TITLE
Parquet Connector not Handling Nulls

### ISSUE THREAD

**Issue by dyaffe** [estuary/connectors#530]
**Problem**
An account is seeing the following issue with our Parquet connector:

`var optional = projection.Inference.Exists != pf.Inference_MUST || !projection.Inference.IsSingleScalarType()`

The account has this field as optional = false, and it’s erroring because it thinks `optional = false` and the instance turns out to be null, but it’s totally possible and allowed for a value to be (for example) a string or null in this case. It can be required to exist, and IsSingleScalarType is true if it’s a nullable types like [string, null]

**Comment by williamhbaker** [comment]
Fixed by https://github.com/estuary/connectors/commit/192fdb1cb3ad9fad96e12920066fc3dcf30de3fa
