### ISSUE TITLE
Google Sheets Materialization Frequency Update

### ISSUE THREAD

**Issue by dyaffe** [estuary/connectors#531]
**Problem**
Our Google Sheets materialization currently runs very quickly (5 updates in a second or so) then exhausts it's resource limit and stops until Google allows it again.  We are about to include this in a UI demo as the first thing everyone sees, so it would be nice to have an always updating materialization that people can watch.

**Proposal**
Update it to only push updates once a second or so -- whatever is the highest frequency that we can continuously do.  I believe that was part of the connector in the past.

**Comment by williamhbaker** [comment]
This seems like a good case for setting the minimum transaction time like we recommend for BigQuery. There's not a super easy way to do that through the UI yet though. It would be nice if connectors could specify values like that in the shard configuration as recommended "defaults" that would be used when setting up the connector through the UI - for sheetings, bigquery, and probably others as well.

**Comment by dyaffe** [comment]
Agreed, would be nice if the connector could do this automatically @williamhbaker.  I can set this value to make the demo work well though for now

**Comment by williamhbaker** [comment]
Closing this since we have hard-coded in this frequency update delay as part of the connector, so this is done
