### ISSUE TITLE
Primary Key Columns on DB Connectors are Confusing

### ISSUE THREAD

**Issue by dyaffe** [estuary/connectors#535]
**Problem** 
We've now seen multiple users have issues with the "Primary Key Columns" connector configuration when their database doesn't have a primary key.

[Here's](https://app.logrocket.com/tue20y/estuarytest/s/5-2b8b8147-bcfa-466c-9101-23aef6d0ab54/0?t=1676033171639.385) an example session and we have others.

**Proposal**
1. Move the current primary key column to advanced and rename it to something that makes it clear that it's not related to the actual primary key.
2. Add a more descriptive error message when someone gets the "no primary key" error which tells users what to do to fix it.

For (2), maybe something like "No primary key found in your collections".  Use the specification editor to add a key to your connector configuration.  -- Alternatively if it's possible for us to break that part out of the specification editor and show it as a configuration box on the collections, that would actually be preferred.  @travjenkins to understand if this would be possible.

**Comment by williamhbaker** [comment]
Closing this since we now support backfills without a primary key and don't have the "Primary Key Columns" configuration anymore.
