### ISSUE TITLE
Elastic Search Requires Additional Properties

### ISSUE THREAD

**Issue by dyaffe** [estuary/connectors#545]
**Problem**
It appears that if there are no additional properties, the elastic search connector is unhappy.  [This](https://app.logrocket.com/tue20y/estuarytest/s/5-2f19c9db-87ac-476e-b6b3-35bba42af886/0?t=1676403684988.3992) session shows the error.

The specific error message is additional properties on an object are not supported, which appears to only come from https://github.com/estuary/flow/blob/master/crates/schemalate/src/elasticsearch/elastic_search_schema_builder.rs#L89

From @willdonnelly -- "It looks like saying additionalProperties: false is the cause of the issue. If I had to guess, the existence of the additionalProperties property may be interpreted as a truth value, when really it should be the other way around (because by default additional properties are permitted, and you have to specify additionalProperties: false to indicate that there really truly shouldn't be anything else)"

**Comment by willdonnelly** [comment]
This is a bug in the `flow-schemalate` binary relating to how it processes an `additionalProperties: false` clause in the schema. I'm going to close this and go file a bug in the Flow repo instead.
