### ISSUE TITLE
Add supported connectors to Flow UI

### ISSUE THREAD

**Issue by jman0119** [estuary/connectors#575]
Similar to this PR (https://github.com/estuary/connectors/pull/525#pullrequestreview-1273636488), the following connectors are supported by Flow but they're not on the Flow UI yet. Can we add these to the UI so that they can be found more easily? They have been tested:

Capture Connectors:
1. Amazon Aurora for Postgres
2. Amazon Aurora for MySQL
3. Azure SQL Server

Materialize Connector:
1. Amazon Aurora for Postgres

**Comment by williamhbaker** [comment]
These are in the connectors table and show up in the UI so I am going to close this out.
