### ISSUE TITLE
materializations: _meta/capture_time

### ISSUE THREAD

**Issue by mdibaiee** [estuary/connectors#579]
There are two approaches that I can see:
1. Adding a synthetic property `captured_at` to the collection when we are writing the document to the collection. We can use `uuid.Clock()` to set the value of this field at this stage. We will also have to make sure we add this field as a projection of the collection.
2. Supporting a synthetic field_selection `_meta/captured_at` without adding the timestamp to the collection, and if the field is included (perhaps we can include it by default as part of recommended field selection), we feed the document to the materialization  with the value of `_meta/captured_at` set to `uuid.Clock()`. (Unclear to me whether we could also support this for derivations easily this way, perhaps we say we don’t support it for derivations and give helper functions in our SQLite derivations to decode and extract the clock from the `uuid`)

A few things to consider:
* I think approach (1) is simpler since it means once we have the projection and the value in the collection, the rest of the steps for materialization and derivations will work as they do with other fields. On the other hand we will have two values in each document that indicate timestamp, one is the `uuid` (if decoded) and the other `captured_at`. However I think if we use the value of `uuid.Clock()` in populating this field, we should be okay to ensure consistency. I’m assuming we do not intend to ever _update_ the uuid of documents.
* With approach (2), connectors that use the `flow_document` field only, will not be able to use this `captured_at` property (i.e. pubsub, mongodb, etc.). It is also _magical_ in the sense that this field will be available only if you specify the field_selection, and it’s not in the `flow_document` property or in the collection.
* With approach (2), we will need to handle this _injection_ of the value into the document before passing it to materializations.
* There was mention of this projection being something like `_meta/uuid/timestamp`, but this projection is invalid according to our own rules: scalar values can’t have properties. I think this would lead to even more _magic_, unless we take a path similar to MongoDB where `uuid` is no longer just a string, but an object which can include other properties, although we may represent it as a string by default. This would be confusing for materializations though, how are they supposed to materialize a string `uuid`, but also materialize a property under it? Perhaps if we _require_ manually specifying the projection, and this projection having to be a valid one (not nested under a scalar) this could work, but it doesn’t feel right to me.
* This also means all our documents will have larger size due to the timestamp being included in all documents.

**Comment by mdibaiee** [comment]
See: https://github.com/estuary/flow/pull/1070

**Comment by williamhbaker** [comment]
Closing this out per `flow_published_at` having been implemented in https://github.com/estuary/flow/pull/1098
