### ISSUE TITLE
materialize-snowflake: snowsql logging errors

### ISSUE THREAD

**Issue by psFried** [estuary/connectors#59]
The materialize-snowflake connector is continuously printing these log messages:

```
Failed to initialize log. No logging is enabled: [Errno 13] Permission denied: '/snowsql_rt.log_bootstrap'
Failed to initialize log. No logging is enabled: [Errno 13] Permission denied: '/snowsql_rt.log'
Failed to initialize log. No logging is enabled: [Errno 13] Permission denied: '/snowsql_rt.log_bootstrap'
Failed to initialize log. No logging is enabled: [Errno 13] Permission denied: '/snowsql_rt.log'
```

[This question](https://stackoverflow.com/questions/64717416/qmacos-error-failed-to-initialize-log-no-logging-is-enabled-errno-13-perm) seems relevant, but there may be other, better options out there.

**Comment by williamhbaker** [comment]
I'm pretty sure this is no longer an issue. I don't see these logs in the connector, and I have also recently disabled logs coming from the `gosnowflake` package internally. It was using `logrus` and would put out some messages that would be really confusing for a user. Going to close this as completed but let me know if I'm missing anything.
