### ISSUE TITLE
removing materialization bindings should delete the table

### ISSUE THREAD

**Issue by mdibaiee** [estuary/connectors#613]
- [x] materialize-postgres
- [x] materialize-snowflake
- [x] materialize-bigquery
- [x] materialize-sqlite
- [x] materialize-s3-parquet
- [ ] materialize-rockset
- [x] materialize-redshift
- [x] materialize-mongodb
- [x] materialize-google-sheets
- [x] materialize-firebolt
- [x] materialize-google-pubsub (not necessary, see comment below)
- [ ] materialize-elasticsearch

**Comment by mdibaiee** [comment]
materialize-sql: https://github.com/estuary/connectors/pull/614

**Comment by williamhbaker** [comment]
If it makes things easier, for `pubsub` I don't think we should actually delete topics when deleting bindings or the materialization. I think delete for `pubsub` could basically be a noop entirely and we can just leave the topics there. It kind of makes sense to not delete published messages that haven't been consumed yet, which is what deleting the topic would do.
