### ISSUE TITLE
CDC connectors should filter well-known flow tables from discovery

### ISSUE THREAD

**Issue by dyaffe** [estuary/connectors#631]
**Problem**
It's relatively common to capture and materialize to the same DB for testing purposes.  When this happens, we capture the three Flow-created tables (watermarks, publications and checkpoints).

It would be nice if we filtered well-known Flow created tables from discovery

**Comment by willdonnelly** [comment]
The materialization tables will need additional logic to be filtered out, but the watermarks table should already be excluded from discovery results. Can you confirm whether the watermarks table was discovered in the test you did earlier?
