### ISSUE TITLE
Update SQL Captures to name collections with schema.table name

### ISSUE THREAD

**Issue by dyaffe** [estuary/connectors#634]
**Problem**
Currently SQL captures name discovered collections with just table names.  This can result in a conflict if two schemas contain the same table name.

**Proposal**
Update discover to output collections with `schema.table` as the postfix of the name

**Comment by jgraettinger** [comment]
When doing this, we should also update the resource config schema to use `schema` instead of `namespace`, which is a hold-over from its Airbyte protocol days.

It will still need to accept `namespace` from deployed capture specs, though.
