### ISSUE TITLE
source-mysql: failed to query latest binlog position on MySQL 5.7

### ISSUE THREAD

**Issue by williamhbaker** [estuary/connectors#682]
`source-mysql` appears to be unable to work with MySQL 5.7.

[Replication stream creation](https://github.com/estuary/connectors/blob/b909a336bc772b571ec7220a3ae2bb3e013b9be6/source-mysql/replication.go#L56) fails with an error like `error creating replication stream: failed to query latest binlog position (is binary logging enabled on "localhost"?)` when trying to run the connector.

This may be a setup issue since 5.7 probably should be able to work with the connector. I also found that some of the commands in our [MySQL setup docs](https://docs.estuary.dev/reference/Connectors/capture-connectors/MySQL/) wouldn't work on a 5.7 database, like `SET PERSIST binlog_expire_logs_seconds = 2592000;` (syntax error), and modify that to `SET binlog_expire_logs_seconds = 2592000;` results in `Unknown system variable 'binlog_expire_logs_seconds'`.

**Comment by dyaffe** [comment]
Checking in on this one -- can we remove the checks for mysql 5.7?  We've seen successful users on it and I have one that wants to go.  It would at least be good to see what fails vs preventing someone from trying.

**Comment by williamhbaker** [comment]
The checks were removed a few weeks ago, via https://github.com/estuary/connectors/pull/812
