### ISSUE TITLE
Request a connector to capture from DynamoDB

### ISSUE THREAD

**Issue by ecoCart123** [estuary/connectors#687]
### System Name

DynamoDB

### Type

Capture

### Details

I want to capture changes in DynamoDB and replicate them to Redshift

**Comment by dyaffe** [comment]
Thanks for the request!  Just a quick question -- have you thought about Amazon's DMS service and is there a reason that wouldn't work for your use case?  We would love to understand that for our prioritization around building the connector.  

Just FYI, usually captures and materializations from NoSQL DB's are relatively quick for us to build (1-2 weeks).

**Comment by ecoCart123** [comment]
Hi there! I had not yet, but thank you for that suggestion. I have been
using fivetran as well as investigating the usage of glue for this process,
but I wanted to ask about dynamoDB with estuary. But the noSQL
differentiation makes a lot of sense in terms of connectors

**Comment by dyaffe** [comment]
Great -- let us know if you're still interested after checking out DMS.  There are some advantages if we were to do it.  A few examples:

1. Lower latency
2. Simpler schematization of your data
3. The ability to push it wherever you want (even outside of AWS)

**Comment by ecoCart123** [comment]
After looking at the cost comparison I would actually love to switch to
estuary if there is a DynamoDB connector! AWS DMS looks useful but I
require support for streaming and low latency. I have been trying to use
glue streaming but having issues with permissions and the high costs of the
glue notebooks using spark, and I think estuary might be a much better
solution than 5tran.

Could I confirm that I'd like estuary to request to add the DynamoDB as a
capture? Once that is added then I think I would be able to switch our
companies data replication service from 5tran to estuary :)

**Comment by dyaffe** [comment]
We don't currently support it but we can prioritize it -- I'll reach out as soon as it's available in the app if that works for you?

**Comment by ecoCart123** [comment]
that sounds great thank you!

**Comment by dyaffe** [comment]
Hey -- quick question for you as we are getting close to releasing these connectors:

Would you want to be able to configure a new value for the partition key and sort key when materializing to DynamoDB or would you want just a partition key?
