### ISSUE TITLE
Request a connector to capture from Shopify

### ISSUE THREAD

**Issue by rob-coherence** [estuary/connectors#895]
### System Name

Shopify

### Type

Capture

### Details

I want to read data from resources regarding orders, line items, inventory etc from the Admin API (https://shopify.dev/docs/api/admin)

**Comment by dyaffe** [comment]
Thanks for the request @rob-coherence -- just a quick question.  Do you have need for a real-time capture?  Either way, could you potentially expand on your use case so that we can prioritize it?

**Comment by dyaffe** [comment]
@rob-coherence this is now available in the platform!

**Comment by williamhbaker** [comment]
Closing this as complete since we now have a shopify capture
