### ISSUE TITLE
Request a connector to capture from and materialize data to Google Cloud Pub/Sub

### ISSUE THREAD

**Issue by ldnicolasmay** [estuary/connectors#945]
### System Name

Google Cloud Pub/Sub

### Type

Both

### Details

I'd like to be able to capture data from and materialize data to Google Cloud Pub/Sub streams.

**Comment by dyaffe** [comment]
@ldnicolasmay, thanks for submitting this request.  Can you expand at all on your use case?  Anything around scalee, use case and destinations would help.  Doing so helps us with prioritization of requests.  

Thanks!
Dave

**Comment by ldnicolasmay** [comment]
Thanks @dyaffe ! 

Definitely put this at the bottom of the priority queue. 

My only use case for now is to try out Estuary/Flow for myself to see if it's something that might be useful at work, where we use GCP, and there's a simulated public Pub/Sub topic that spits out NYC taxi data (`projects/pubsub-public-data/topics/taxirides-realtime`) that I was thinking to try out. (Example here: https://cloud.google.com/dataflow/docs/quickstarts/create-streaming-pipeline-template?hl=en)

As far as a destination, I don't have anything specific in mind other than using BigQuery as a sink (which I know is already easily possible using a Dataflow template) and/or Google Sheets, because how else do you demo stuff or sell ideas to people without updating spreadsheets (lol).

**Comment by dyaffe** [comment]
Thanks @ldnicolasmay -- appreciate the detail and we'll get back to you when we have more info.

**Comment by williamhbaker** [comment]
We now have a Pub/Sub capture and materialization, so I am closing this out as done.
